version: "2"
services:
  tomcat1:
    build: tomcat9
    env_file:
      .env
    container_name: builder
    volumes:
      - /opt/share/:/opt/
  #  volumes:
  #    - D:\\учеба\\DevOps\\git\\test\\share/:/opt/
 #   command: ["/bin/sh", "-c", "cp /usr/local/tomcat/boxfuse-sample-java-war-hello/target /tmp"]  
 #          /usr/local/tomcat/boxfuse-sample-java-war-hello/target
 #  command:
 #     sh "cp /usr/local/tomcat/usr/local/tomcat/boxfuse-sample-java-war-hello/hello-1.0.war /tmp"


      
  tomcat2:
    build: prod
    ports:
      - "5555:8080"
    container_name: prod
    env_file:
      .env
  #  volumes:
  #    - :/opt/
    depends_on:
      - "tomcat1"
    #command: ["bash", "cp /tmp/hello-1.0.war /usr/local/tomcat/webapps/"]  
    
 
              
