version: "3"
services:
  install:
    build: install
    container_name: install
    volumes:
      - type: volume
        source: war
        target: /boxfuse-sample-java-war-hello/target/

  run:
    build: prod
    container_name: prod
    volumes:
      - type: volume
        source: war
        target: /usr/local/tomcat/webapps/
    ports:
      - 5555:8080
    depends_on:
      - install

volumes:
  war: